# Generated by Django 5.0.7 on 2024-11-25 06:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todo_description_remove_todo_user_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user_identifier',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
    ]
